import type { Completion, CompletionContext, CompletionResult } from "@codemirror/autocomplete";
import type { Extension } from "@codemirror/state";
import { EditorState, Facet } from "@codemirror/state";

/**
 * Module/header completion for import statements, mirroring what VS Code's
 * language servers surface: toolchain-enumerated stdlib datasets (generated by
 * scripts/gen-import-data.mjs) plus relative-path completion from the
 * workspace file tree.
 */

type ImportData = typeof import("./import-data");

let dataPromise: Promise<ImportData> | null = null;
function loadData(): Promise<ImportData> {
  dataPromise ??= import("./import-data");
  return dataPromise;
}

// ---- workspace file registry (for relative-path completion) ----

let workspaceFiles: string[] = [];

/** Host registers its file tree (full paths, e.g. "src/util/api.ts"). */
export function setWorkspaceFiles(paths: string[]): void {
  workspaceFiles = paths;
}

const importFilePath = Facet.define<string, string>({
  combine: (values) => values[0] ?? "",
});

function dirOf(path: string): string {
  const i = path.lastIndexOf("/");
  return i < 0 ? "" : path.slice(0, i);
}

function normalize(parts: string[]): string[] {
  const out: string[] = [];
  for (const p of parts) {
    if (p === "" || p === ".") continue;
    if (p === "..") out.pop();
    else out.push(p);
  }
  return out;
}

/**
 * VS Code-style path completion: given the typed prefix ("./", "../lib/"),
 * offer the files and directories that actually exist at that location.
 */
function relativeCompletions(
  state: EditorState,
  typed: string,
  stripExts: readonly string[],
): Completion[] {
  if (!workspaceFiles.length) return [];
  const from = state.facet(importFilePath);
  const baseDir = dirOf(from);
  const lastSlash = typed.lastIndexOf("/");
  const typedDir = lastSlash < 0 ? "" : typed.slice(0, lastSlash);
  const resolved = normalize([...baseDir.split("/"), ...typedDir.split("/")]).join("/");
  const prefix = resolved ? `${resolved}/` : "";
  const seen = new Map<string, Completion>();
  for (const file of workspaceFiles) {
    if (file === from || !file.startsWith(prefix)) continue;
    const rest = file.slice(prefix.length);
    const slash = rest.indexOf("/");
    if (slash >= 0) {
      const dir = rest.slice(0, slash);
      const label = `${typedDir ? `${typedDir}/` : ""}${dir}/`;
      if (!seen.has(label)) seen.set(label, { label, type: "namespace", boost: 1 });
    } else {
      let name = rest;
      for (const ext of stripExts) {
        if (name.endsWith(ext)) {
          name = name.slice(0, -ext.length);
          break;
        }
      }
      const label = `${typedDir ? `${typedDir}/` : ""}${name}`;
      if (!seen.has(label)) seen.set(label, { label, type: "module" });
    }
  }
  return [...seen.values()];
}

const toOptions = (names: readonly string[], boost = 0): Completion[] =>
  names.map((label) => ({ label, type: "module", boost }));

function result(context: CompletionContext, from: number, options: Completion[]): CompletionResult | null {
  if (!options.length) return null;
  return { from, options, validFor: /^[\w./@:-]*$/ };
}

// ---- per-language sources ----

async function pythonSource(context: CompletionContext): Promise<CompletionResult | null> {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const m =
    /^\s*(?:import|from)\s+([\w.]*)$/.exec(before) ??
    /^\s*import\s+[\w.]+\s*,\s*([\w.]*)$/.exec(before);
  if (!m && !context.explicit) return null;
  if (!m) return null;
  const { PYTHON_STDLIB } = await loadData();
  return result(context, context.pos - m[1].length, toOptions(PYTHON_STDLIB));
}

async function jsSource(context: CompletionContext): Promise<CompletionResult | null> {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const m =
    /(?:import|export)\s+(?:[\w{},*\s$]+\s+from\s+)?["']([^"']*)$/.exec(before) ??
    /(?:require|import)\s*\(\s*["']([^"']*)$/.exec(before);
  if (!m) return null;
  const typed = m[1];
  const from = context.pos - typed.length;
  if (typed.startsWith(".") || typed.startsWith("/")) {
    return result(
      context,
      from,
      relativeCompletions(context.state, typed, [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]),
    );
  }
  const { NODE_BUILTINS } = await loadData();
  const options = [
    ...toOptions(NODE_BUILTINS, 1),
    ...NODE_BUILTINS.map((label) => ({ label: `node:${label}`, type: "module" as const })),
  ];
  return result(context, from, options);
}

async function cSource(context: CompletionContext, cpp: boolean): Promise<CompletionResult | null> {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const m = /^\s*#\s*include\s*(<|")([^">]*)$/.exec(before);
  if (!m) return null;
  const typed = m[2];
  const from = context.pos - typed.length;
  if (m[1] === '"') {
    const rel = relativeCompletions(context.state, typed || "./", []);
    if (rel.length) return result(context, from, rel);
  }
  const data = await loadData();
  return result(context, from, toOptions(cpp ? data.CPP_HEADERS : data.C_HEADERS));
}

async function goSource(context: CompletionContext): Promise<CompletionResult | null> {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const inline = /^\s*import\s+(?:\w+\s+)?"([^"]*)$/.exec(before);
  let m = inline;
  if (!m) {
    const block = /^\s*(?:\w+\s+)?"([^"]*)$/.exec(before);
    if (block && isInsideGoImportBlock(context)) m = block;
  }
  if (!m) return null;
  const { GO_STDLIB } = await loadData();
  return result(context, context.pos - m[1].length, toOptions(GO_STDLIB));
}

function isInsideGoImportBlock(context: CompletionContext): boolean {
  const doc = context.state.doc;
  const current = doc.lineAt(context.pos).number;
  for (let i = current - 1; i >= 1 && current - i < 200; i--) {
    const text = doc.line(i).text;
    if (/^\s*import\s*\(\s*$/.test(text)) return true;
    if (/\)/.test(text) || /^\s*(func|var|const|type)\b/.test(text)) return false;
  }
  return false;
}

async function rubySource(context: CompletionContext): Promise<CompletionResult | null> {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const m = /^\s*require(?:_relative)?\s*\(?\s*["']([^"']*)$/.exec(before);
  if (!m) return null;
  const typed = m[1];
  const from = context.pos - typed.length;
  if (before.includes("require_relative") || typed.startsWith(".")) {
    return result(context, from, relativeCompletions(context.state, typed, [".rb"]));
  }
  const { RUBY_STDLIB } = await loadData();
  return result(context, from, toOptions(RUBY_STDLIB));
}

const SOURCES: Record<string, (context: CompletionContext) => Promise<CompletionResult | null>> = {
  python: pythonSource,
  javascript: jsSource,
  javascriptreact: jsSource,
  typescript: jsSource,
  typescriptreact: jsSource,
  c: (ctx) => cSource(ctx, false),
  cpp: (ctx) => cSource(ctx, true),
  go: goSource,
  ruby: rubySource,
};

/** Languages that get import/include completion. */
export function hasImportCompletions(langId: string): boolean {
  return langId in SOURCES;
}

/**
 * Editor extension: attaches the language's import completion source plus the
 * current file path (used to resolve relative-path completions).
 */
export function importCompletions(langId: string, filePath: string): Extension {
  const source = SOURCES[langId];
  if (!source) return [];
  return [
    importFilePath.of(filePath),
    EditorState.languageData.of(() => [{ autocomplete: source }]),
  ];
}
