import { useEffect, useRef } from "react";
import { HyperScroll, type DataSource } from "@hyperscroll/core";
import { codeLinePx } from "./editor/scale";
 
export const HYPER_COUNT = 10_000_000;
const LINES_PER_CLASS = 20;
 
const CS_KEYWORDS = new Set(
  "abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach get goto if implicit in init int interface internal is lock long namespace new not null object operator out override params partial private protected public readonly record ref required return sbyte sealed set short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using var virtual void volatile while yield async await when where with".split(" ")
);
 
function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
 
const TOKEN_RE = /(\/\/.*$)|("(?:[^"\\]|\\.)*"|\$"(?:[^"\\]|\\.)*")|(\b\d[\d_]*(?:\.\d+)?[mfdL]?\b)|([A-Za-z_][A-Za-z0-9_]*)/gm;
 
export function highlightCs(line: string): string {
  let out = "";
  let last = 0;
  for (const m of line.matchAll(TOKEN_RE)) {
    const i = m.index;
    out += esc(line.slice(last, i));
    const [full, comment, str, num, ident] = m;
    if (comment) out += `<span class="tk-c">${esc(comment)}</span>`;
    else if (str) out += `<span class="tk-s">${esc(str)}</span>`;
    else if (num) out += `<span class="tk-n">${esc(num)}</span>`;
    else if (ident) {
      if (CS_KEYWORDS.has(ident)) out += `<span class="tk-k">${esc(ident)}</span>`;
      else if (line[i + full.length] === "(") out += `<span class="tk-f">${esc(ident)}</span>`;
      else if (/^[A-Z]/.test(ident)) out += `<span class="tk-t">${esc(ident)}</span>`;
      else out += esc(ident);
    }
    last = i + full.length;
  }
  out += esc(line.slice(last));
  return out;
}
 
/** Deterministic generated C# source: line i of a 10M-line partial class file. */
export function generatedLine(i: number): string {
  const cls = Math.floor(i / LINES_PER_CLASS);
  switch (i % LINES_PER_CLASS) {
    case 0: return `// <auto-generated> Entity ${cls} — Lumen.CodeGen v3.2 </auto-generated>`;
    case 1: return `public sealed partial class Entity${cls} : IEntity, IEquatable<Entity${cls}>`;
    case 2: return `{`;
    case 3: return `    public long Id { get; init; } = ${cls}L;`;
    case 4: return `    public string Name { get; set; } = "entity-${cls}";`;
    case 5: return `    public decimal Amount { get; set; } = ${(cls % 9000) + 0.99}m;`;
    case 6: return `    private readonly Dictionary<string, object?> _extensions = new();`;
    case 7: return ``;
    case 8: return `    public bool Equals(Entity${cls}? other) => other is not null && Id == other.Id;`;
    case 9: return `    public override int GetHashCode() => HashCode.Combine(Id, Name);`;
    case 10: return ``;
    case 11: return `    public async Task<ValidationResult> ValidateAsync(CancellationToken ct = default)`;
    case 12: return `    {`;
    case 13: return `        if (string.IsNullOrWhiteSpace(Name))`;
    case 14: return `            return ValidationResult.Fail("name is required"); // rule N-${cls % 64}`;
    case 15: return `        await Task.Yield();`;
    case 16: return `        return Amount >= 0m ? ValidationResult.Ok : ValidationResult.Fail("negative amount");`;
    case 17: return `    }`;
    case 18: return `}`;
    default: return ``;
  }
}
 
export function HyperViewer() {
  const viewportRef = useRef<HTMLDivElement>(null);
  const engineRef = useRef<HyperScroll | null>(null);
  const editsRef = useRef(new Map<number, string>());
 
  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;
    const edits = editsRef.current;
    const cache = new Map<number, string>();
    const source: DataSource = {
      count: HYPER_COUNT,
      renderToString: (i) => {
        if (!edits.has(i)) {
          const hit = cache.get(i);
          if (hit) return hit;
        }
        const text = edits.has(i) ? edits.get(i)! : generatedLine(i);
        const edited = edits.has(i) ? " edited" : "";
        const html = `<div class="hx-line${edited}" data-index="${i}"><span class="ln">${(i + 1).toLocaleString()}</span><span class="hx-code">${highlightCs(text)}</span></div>`;
        if (!edits.has(i)) {
          if (cache.size > 60_000) cache.clear();
          cache.set(i, html);
        }
        return html;
      },
      estimateHeight: () => codeLinePx(),
    };
    const engine = new HyperScroll(el, {
      dataSource: source,
      keyboard: true,
      estimatedItemHeight: codeLinePx(),
      upCount: 400,
      overscanPx: 16000,
    });
    engineRef.current = engine;
 
    interface EditState { index: number; value: string; selStart: number; selEnd: number }
    let editing: EditState | null = null;
 
    const persist = (state: EditState) => {
      if (state.value !== generatedLine(state.index)) edits.set(state.index, state.value);
      else edits.delete(state.index);
    };
 
    const mountInput = (lineEl: HTMLElement, state: EditState) => {
      const code = lineEl.querySelector(".hx-code");
      if (!code) return;
      const input = document.createElement("input");
      input.className = "hx-line-input";
      input.value = state.value;
      input.spellcheck = false;
      code.replaceWith(input);
      input.focus({ preventScroll: true });
      input.setSelectionRange(state.selStart, state.selEnd);
      const trackSel = () => {
        state.selStart = input.selectionStart ?? state.selStart;
        state.selEnd = input.selectionEnd ?? state.selEnd;
      };
      input.addEventListener("input", () => {
        state.value = input.value;
        trackSel();
      });
      input.addEventListener("keyup", trackSel);
      input.addEventListener("mouseup", trackSel);
      input.addEventListener("keydown", (ke) => {
        if (ke.key === "Enter" || ke.key === "ArrowDown") {
          ke.preventDefault(); ke.stopPropagation();
          moveEditing(state.index + 1);
        } else if (ke.key === "ArrowUp") {
          ke.preventDefault(); ke.stopPropagation();
          moveEditing(state.index - 1);
        } else if (ke.key === "Escape") {
          ke.stopPropagation();
          editing = null;
          engine.refresh();
          sync();
        } else {
          ke.stopPropagation();
        }
      });
      input.addEventListener("blur", () => {
        if (!input.isConnected) return;
        if (editing && editing.index === state.index) {
          persist(state);
          editing = null;
          engine.refresh();
          sync();
        }
      });
    };
 
    const sync = () => {
      el.querySelectorAll<HTMLElement>(".hx-line.editing").forEach((n) => {
        if (!editing || Number(n.dataset.index) !== editing.index) {
          n.classList.remove("editing");
        }
      });
      if (!editing) return;
      const lineEl = el.querySelector<HTMLElement>(`.hx-line[data-index="${editing.index}"]`);
      if (!lineEl) return;
      lineEl.classList.add("editing");
      if (!lineEl.querySelector("input")) mountInput(lineEl, editing);
    };
 
    const startEditing = (index: number, caret?: number) => {
      if (index < 0 || index >= HYPER_COUNT) return;
      if (editing) persist(editing);
      const current = edits.has(index) ? edits.get(index)! : generatedLine(index);
      const sel = Math.min(caret ?? current.length, current.length);
      editing = { index, value: current, selStart: sel, selEnd: sel };
      engine.refresh();
      sync();
      requestAnimationFrame(sync);
    };
 
    const moveEditing = (index: number) => {
      if (!editing) return;
      startEditing(index, editing.selStart);
    };
 
    const observer = new MutationObserver(sync);
    observer.observe(el, { childList: true, subtree: true });
 
    const onClick = (e: MouseEvent) => {
      const lineEl = (e.target as HTMLElement).closest?.(".hx-line") as HTMLElement | null;
      if (!lineEl || lineEl.querySelector("input")) return;
      startEditing(Number(lineEl.dataset.index));
    };
    el.addEventListener("click", onClick);
 
    return () => {
      observer.disconnect();
      el.removeEventListener("click", onClick);
      engine.destroy();
      engineRef.current = null;
    };
  }, []);
 
  return <div ref={viewportRef} className="hyper-viewport" />;
}
