import { memo, useEffect, useRef } from "react";
import { EditorView } from "@codemirror/view";
import { EditorState, Compartment, StateEffect, type Extension } from "@codemirror/state";
import {
  keymap,
  lineNumbers,
  drawSelection,
  highlightActiveLine,
  highlightActiveLineGutter,
  highlightSpecialChars,
  ViewPlugin,
} from "@codemirror/view";
import { defaultKeymap, history, historyKeymap, indentWithTab } from "@codemirror/commands";
import { bracketMatching, indentOnInput, indentUnit } from "@codemirror/language";
import { closeBrackets, closeBracketsKeymap } from "@codemirror/autocomplete";
import { searchKeymap, highlightSelectionMatches } from "@codemirror/search";
import { smoothCaret } from "./editor/caret";
import { editorTheme } from "./editor/theme";
import type { CursorInfo } from "./Editor";
 
export const HYPER_COUNT = 10_000_000;
const LINES_PER_CLASS = 20;
const CHUNK = 2_000;
const CHUNKS = HYPER_COUNT / CHUNK;
const WINDOW_CHUNKS = 3;

let csharpLanguagePromise: Promise<Extension> | null = null;
const deferredCsharpLanguage = ViewPlugin.define((view) => {
  let active = true;
  csharpLanguagePromise ??= import("./editor/csharp").then((module) => module.csharpLanguage);
  void csharpLanguagePromise.then(
    (language) => {
      if (active) view.dispatch({ effects: StateEffect.appendConfig.of(language) });
    },
    (error: unknown) => console.error("Failed to load HyperEditor C# support", error)
  );
  return { destroy: () => { active = false; } };
});
 
/** Deterministic generated C# source: line i of a 10M-line partial class file. */
export function generatedLine(i: number): string {
  const cls = Math.floor(i / LINES_PER_CLASS);
  switch (i % LINES_PER_CLASS) {
    case 0: return `// <auto-generated> Entity ${cls} — Lumen.CodeGen v3.2 </auto-generated>`;
    case 1: return `public sealed partial class Entity${cls} : IEntity, IEquatable<Entity${cls}>`;
    case 2: return `{`;
    case 3: return `    public long Id { get; init; } = ${cls}L;`;
    case 4: return `    public string Name { get; set; } = "entity-${cls}";`;
    case 5: return `    public decimal Amount { get; set; } = ${(cls % 9000) + 0.99}m;`;
    case 6: return `    private readonly Dictionary<string, object?> _extensions = new();`;
    case 7: return ``;
    case 8: return `    public bool Equals(Entity${cls}? other) => other is not null && Id == other.Id;`;
    case 9: return `    public override int GetHashCode() => HashCode.Combine(Id, Name);`;
    case 10: return ``;
    case 11: return `    public async Task<ValidationResult> ValidateAsync(CancellationToken ct = default)`;
    case 12: return `    {`;
    case 13: return `        if (string.IsNullOrWhiteSpace(Name))`;
    case 14: return `            return ValidationResult.Fail("name is required"); // rule N-${cls % 64}`;
    case 15: return `        await Task.Yield();`;
    case 16: return `        return Amount >= 0m ? ValidationResult.Ok : ValidationResult.Fail("negative amount");`;
    case 17: return `    }`;
    case 18: return `}`;
    default: return ``;
  }
}
 
/** Sparse chunk overrides — only chunks the user actually edited are stored. */
const editedChunks = new Map<number, string>();
const editedChunkLineDeltas = new Map<number, number>();
let totalLineDelta = 0;
const generatedChunkCache = new Map<number, string>();
const GENERATED_CACHE_LIMIT = WINDOW_CHUNKS + 2;
 
function generatedChunkText(idx: number): string {
  const cached = generatedChunkCache.get(idx);
  if (cached !== undefined) {
    generatedChunkCache.delete(idx);
    generatedChunkCache.set(idx, cached);
    return cached;
  }
  const start = idx * CHUNK;
  const parts: string[] = [];
  for (let i = 0; i < CHUNK; i++) parts.push(generatedLine(start + i));
  const text = parts.join("\n");
  generatedChunkCache.set(idx, text);
  if (generatedChunkCache.size > GENERATED_CACHE_LIMIT) {
    generatedChunkCache.delete(generatedChunkCache.keys().next().value!);
  }
  return text;
}
 
function chunkText(idx: number): string {
  return editedChunks.get(idx) ?? generatedChunkText(idx);
}
 
function linesBeforeChunk(idx: number): number {
  let lines = idx * CHUNK;
  for (const [k, delta] of editedChunkLineDeltas) if (k < idx) lines += delta;
  return lines;
}
 
function totalLines(): number {
  return HYPER_COUNT + totalLineDelta;
}

function lineDelta(text: string): number {
  let lines = 1;
  for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) lines++;
  return lines - CHUNK;
}

function storeEditedChunk(idx: number, text: string): void {
  const previousDelta = editedChunkLineDeltas.get(idx) ?? 0;
  if (text === generatedChunkText(idx)) {
    editedChunks.delete(idx);
    editedChunkLineDeltas.delete(idx);
    totalLineDelta -= previousDelta;
    return;
  }
  const nextDelta = lineDelta(text);
  editedChunks.set(idx, text);
  editedChunkLineDeltas.set(idx, nextDelta);
  totalLineDelta += nextDelta - previousDelta;
}
 
interface HyperEditorProps {
  dark: boolean;
  onCursor: (info: CursorInfo) => void;
}
 
export const HyperEditor = memo(function HyperEditor({ dark, onCursor }: HyperEditorProps) {
  const hostRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);
  const themeCompartment = useRef(new Compartment());
  const gutterCompartment = useRef(new Compartment());
  const onCursorRef = useRef(onCursor);
  onCursorRef.current = onCursor;
  const darkRef = useRef(dark);
 
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
 
    let firstChunk = 0;
    /** Doc offsets where each window chunk starts (length WINDOW_CHUNKS). */
    let boundaries: number[] = [];
    let windowStartLine = 0;
    let swapping = false;
 
    const windowChunkCount = () => Math.min(WINDOW_CHUNKS, CHUNKS - firstChunk);
 
    const buildDoc = (): string => {
      const parts: string[] = [];
      boundaries = [];
      let off = 0;
      for (let k = 0; k < windowChunkCount(); k++) {
        boundaries.push(off);
        const text = chunkText(firstChunk + k);
        parts.push(text);
        off += text.length + 1;
      }
      windowStartLine = linesBeforeChunk(firstChunk);
      return parts.join("\n");
    };
 
    const gutter = () =>
      lineNumbers({
        formatNumber: (n) => (windowStartLine + n).toLocaleString(),
      });
 
    const commitWindow = (state: EditorState) => {
      for (let k = 0; k < windowChunkCount(); k++) {
        const from = boundaries[k];
        const to = k + 1 < boundaries.length ? boundaries[k + 1] - 1 : state.doc.length;
        const text = state.doc.sliceString(from, to);
        const idx = firstChunk + k;
        if (text !== editedChunks.get(idx)) storeEditedChunk(idx, text);
      }
    };
 
    const reportCursor = (state: EditorState) => {
      const head = state.selection.main.head;
      const line = state.doc.lineAt(head);
      onCursorRef.current({
        line: windowStartLine + line.number,
        col: head - line.from + 1,
        length: totalLines(),
        selections: state.selection.ranges.length,
      });
    };
 
    const extensions = [
      gutterCompartment.current.of(gutter()),
      highlightActiveLineGutter(),
      highlightSpecialChars(),
      history(),
      drawSelection(),
      EditorState.allowMultipleSelections.of(true),
      indentOnInput(),
      bracketMatching(),
      closeBrackets(),
      highlightActiveLine(),
      highlightSelectionMatches(),
      keymap.of([...closeBracketsKeymap, ...defaultKeymap, ...searchKeymap, ...historyKeymap, indentWithTab]),
      indentUnit.of("    "),
      deferredCsharpLanguage,
      smoothCaret(),
      themeCompartment.current.of(editorTheme(darkRef.current)),
      EditorView.updateListener.of((update) => {
        if (update.docChanged && !swapping) {
          boundaries = boundaries.map((b) => update.changes.mapPos(b, 1));
        }
        if (update.selectionSet || update.docChanged) reportCursor(update.state);
      }),
    ];
 
    const view = new EditorView({
      parent: host,
      state: EditorState.create({ doc: buildDoc(), extensions }),
    });
    viewRef.current = view;
 
    const lineHeight = () => view.defaultLineHeight;
 
    /** Rebuild the whole window around a global line and scroll it into place. */
    const jumpToLine = (globalLine: number) => {
      commitWindow(view.state);
      const target = Math.max(0, Math.min(totalLines() - 1, globalLine));
      firstChunk = Math.max(0, Math.min(CHUNKS - WINDOW_CHUNKS, Math.floor(target / CHUNK) - 1));
      swapping = true;
      view.setState(EditorState.create({ doc: buildDoc(), extensions }));
      view.dispatch({ effects: gutterCompartment.current.reconfigure(gutter()) });
      swapping = false;
      view.scrollDOM.scrollTop = (target - windowStartLine) * lineHeight();
      updateThumb();
      reportCursor(view.state);
    };
 
    /** Slide window one chunk up/down, preserving scroll position and selection. */
    const shift = (dir: 1 | -1) => {
      if (dir === 1 && firstChunk + WINDOW_CHUNKS >= CHUNKS) return;
      if (dir === -1 && firstChunk === 0) return;
      swapping = true;
      commitWindow(view.state);
      const oldScroll = view.scrollDOM.scrollTop;
      const oldStart = windowStartLine;
      const selHead = view.state.selection.main.head;
      const selLine = view.state.doc.lineAt(selHead);
      const globalSelLine = oldStart + selLine.number;
      const selCol = selHead - selLine.from;
 
      firstChunk += dir;
      const doc = buildDoc();
      const state = EditorState.create({ doc, extensions });
      // restore selection at same global line when still inside window
      const relLine = globalSelLine - windowStartLine;
      let selection;
      if (relLine >= 1 && relLine <= state.doc.lines) {
        const l = state.doc.line(relLine);
        const pos = Math.min(l.from + selCol, l.to);
        selection = { anchor: pos };
      }
      view.setState(selection ? EditorState.create({ doc, extensions, selection }) : state);
      view.dispatch({ effects: gutterCompartment.current.reconfigure(gutter()) });
      view.scrollDOM.scrollTop = oldScroll - (windowStartLine - oldStart) * lineHeight();
      swapping = false;
      updateThumb();
    };
 
    // ---- custom full-range scrollbar ----
    const bar = document.createElement("div");
    bar.className = "hyper-scrollbar";
    const thumb = document.createElement("div");
    thumb.className = "hyper-scrollbar-thumb";
    bar.appendChild(thumb);
    host.appendChild(bar);
 
    const globalTopLine = () => windowStartLine + view.scrollDOM.scrollTop / lineHeight();
 
    const updateThumb = () => {
      const total = totalLines();
      const viewLines = view.scrollDOM.clientHeight / lineHeight();
      const trackH = bar.clientHeight;
      const thumbH = Math.max(24, (viewLines / total) * trackH);
      const maxTop = trackH - thumbH;
      const ratio = Math.min(1, globalTopLine() / Math.max(1, total - viewLines));
      thumb.style.height = `${thumbH}px`;
      thumb.style.transform = `translateY(${ratio * maxTop}px)`;
    };

    let thumbFrame = 0;
    const scheduleThumbUpdate = () => {
      if (!thumbFrame) {
        thumbFrame = window.requestAnimationFrame(() => {
          thumbFrame = 0;
          updateThumb();
        });
      }
    };
 
    let dragging: { startY: number; startRatio: number } | null = null;
    const ratioToLine = (ratio: number) => {
      const total = totalLines();
      const viewLines = view.scrollDOM.clientHeight / lineHeight();
      return Math.max(0, Math.min(1, ratio)) * (total - viewLines);
    };
    thumb.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      thumb.setPointerCapture(e.pointerId);
      const total = totalLines();
      const viewLines = view.scrollDOM.clientHeight / lineHeight();
      dragging = { startY: e.clientY, startRatio: globalTopLine() / Math.max(1, total - viewLines) };
    });
    thumb.addEventListener("pointermove", (e) => {
      if (!dragging) return;
      const trackH = bar.clientHeight - thumb.clientHeight;
      const ratio = dragging.startRatio + (e.clientY - dragging.startY) / Math.max(1, trackH);
      jumpToLine(Math.round(ratioToLine(ratio)));
    });
    thumb.addEventListener("pointerup", () => (dragging = null));
    bar.addEventListener("pointerdown", (e) => {
      if (e.target !== bar) return;
      const rect = bar.getBoundingClientRect();
      jumpToLine(Math.round(ratioToLine((e.clientY - rect.top) / rect.height)));
    });
 
    // ---- keep window sliding while the user scrolls natively ----
    const onScroll = () => {
      if (swapping) return;
      scheduleThumbUpdate();
      const topLine = view.scrollDOM.scrollTop / lineHeight();
      const docLines = view.state.doc.lines;
      const viewLines = view.scrollDOM.clientHeight / lineHeight();
      if (firstChunk > 0 && topLine < CHUNK * 0.5) shift(-1);
      else if (firstChunk + WINDOW_CHUNKS < CHUNKS && topLine + viewLines > docLines - CHUNK * 0.5) shift(1);
    };
    view.scrollDOM.addEventListener("scroll", onScroll);
 
    reportCursor(view.state);
    scheduleThumbUpdate();
    view.focus();
 
    return () => {
      commitWindow(view.state);
      if (thumbFrame) window.cancelAnimationFrame(thumbFrame);
      view.scrollDOM.removeEventListener("scroll", onScroll);
      bar.remove();
      view.destroy();
      viewRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
 
  useEffect(() => {
    darkRef.current = dark;
    viewRef.current?.dispatch({
      effects: themeCompartment.current.reconfigure(editorTheme(dark)),
    });
  }, [dark]);
 
  return <div ref={hostRef} className="editor-pane hyper-cm" />;
});
